services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pollhub
      POSTGRES_USER: pollhub
      POSTGRES_PASSWORD: pollhub_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pollhub"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    ports:
      - "8082:8080"

  backend:
    build: ./backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: pollhub
      POSTGRES_USER: pollhub
      POSTGRES_PASSWORD: pollhub_secret
      REDIS_HOST: redis
      # Issuer = ce que voit le navigateur (présent dans le token)
      KEYCLOAK_ISSUER_URI: http://localhost:8082/realms/pollhub
      # Clés de signature = récupérées via le réseau Docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/pollhub/protocol/openid-connect/certs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: